name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug - List Files in Workspace
      run: ls -alh

    - name: Build and Push Docker Image
      run: |
        cd Mocab.Web.API.Services  # Navigate to the directory containing the Dockerfile
        docker build -t cjarmas/mocab-web-services .
        docker push cjarmas/mocab-web-services
