name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Navigate To Dockerfile Directory
    #  run: cd Mocab.Web.Services

    - name: Debug - List Files in Workspace
      run: ls -alh

    - name: Build and Push Docker Image
      run: |
        # Navigate to the directory containing the Dockerfile
        cd Mocab.Web.Services

        # Build and push the multi-platform image
        docker buildx build --platform linux/arm64 \
          -t cjarmas/mocab-web-services:latest \
          --push .
