name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug - List Files in Workspace
      run: ls -alh

    #- name: Build and Push Docker Image
    #  run: |
    #    cd Mocab.Web.Services  # Navigate to the directory containing the Dockerfile
    #    docker build -t cjarmas/mocab-web-services .
    #    docker push cjarmas/mocab-web-services

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: |
          echo ¡Hello World SSH!
